spring:
  datasource:
    url: jdbc:mysql://192.168.18.64:3306/example
    username: root
    password: 123456

logging:
  level:
    root: debug

tomato:
  mybatis:
    sql:
      analysis:
        analysis-switch: true
        replace-switch: true
